language: pillar
sudo: false
addons:
  apt:
    packages:
    - libc6-i386
install:
  - mkdir -p /tmp/texlive && cd /tmp/texlive && wget https://gist.github.com/urdh/ca8ffcf7cb7c6eace9ad/raw/57718dd299f2e0cd4a2966c17222330624ec9383/texlive.profile && wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz && tar -xvf install-tl-unx.tar.gz && cd install-tl-* && TEXLIVE_INSTALL_PREFIX=/tmp/texlive ./install-tl --profile=../texlive.profile
  - cd $TRAVIS_BUILD_DIR
  - ./download.sh

script:
  - PATH=/tmp/texlive/CURRENT/bin/x86_64-linux:$PATH ./compile.sh
